### ISSUE TITLE
Normal map tiles?

### ISSUE THREAD

**Issue by prolink007** [cgcostume/pubg-maps#1]
Can this be used to extract normal map tiles from PUBG? Instead of just height data? I am wanting to extract the map tiles to show the map like you would see it in game.

**Comment by cgcostume** [comment]
yes, both normal and height data are extracted and provided, the script extracts all 256 tiles (for height and normal each) and stitches them together

**Comment by cgcostume** [comment]
oh - did you mean albedo/color/diffuse channels for the maps, so basically the textured version of it? i assumed you meant normal maps (as in https://en.wikipedia.org/wiki/Normal_mapping). So albedo/color/diffuse are currently not extracted.

**Comment by nalmeth** [comment]
I'm pretty sure that's what they meant. Is there any way to adapt this to extract/create the textured maps? I've been trying to work on mapping some things in pubg, but for the life of me I can't figure out where some sites (like https://pubgmap.io/) have gotten their high resolution maps.

**Comment by Blenux** [comment]
nalmeth - Pretty sure it's just the 8k Map for that pubgmap site above, like same map when you Press M for ingame map etc.

Check /UI/HUD/Erangel_Minimap_new.uasset with uModel....

**Comment by nalmeth** [comment]
Very well could be. Thanks for pointing me to those.

**Comment by Blenux** [comment]
No worries, got the erangel map in, now got to work  out the terrain materials.

**Comment by cgcostume** [comment]
With respect to a single, final-color texture: usually the terrain is textured within the game on-the-fly, i.e., 
- there are either lookup-maps referencing the texture that is to be used at any point, 
- and/or the height/tangent/normal is used to derive a specific ground texture
- and/or a base color is used to be blended with the specific texture somehow 
- and/or there are often detail maps added to provide/fake additional detail ...

So it is unlikely (and i did not find one) that there is a pre-computed full texture map. Furthermore, such a map had to be much bigger than the 8k - since a single pixel in the map covers aprox. a 'meter' within the game and would require much more texture detail...

**Comment by Blenux** [comment]
Epic have mention in a blog update that they are working on a new ingame map with higher quality textures.
