### ISSUE TITLE
map 3 sanhok

### ISSUE THREAD

**Issue by cashmeouside** [cgcostume/pubg-maps#2]
Hi,

Thank you for the DIY! Can you help with the new map Sahok aka savage? The heightmap files are exported slightly different for it. When I try to modify the python to allow for it I end up with an image with stitching that is off. I'm not sure how to adjust the script accordingly.

File structure of new map(the old maps are HeightMap_x0_y0_01_sharedAssets):

HeightMap_x0_y0_sharedAssets
HeightMap_x0_y1_sharedAssets
HeightMap_x0_y2_sharedAssets
HeightMap_x0_y3_sharedAssets
HeightMap_x1_y0_sharedAssets
HeightMap_x1_y1_sharedAssets
HeightMap_x1_y2_sharedAssets
HeightMap_x1_y3_sharedAssets
HeightMap_x2_y0_sharedAssets
HeightMap_x2_y1_sharedAssets
HeightMap_x2_y2_sharedAssets
HeightMap_x2_y3_sharedAssets
HeightMap_x3_y0_sharedAssets
HeightMap_x3_y1_sharedAssets
HeightMap_x3_y2_sharedAssets
HeightMap_x3_y3_sharedAssets

my modifications:

tslHeightmapPathsByMap =  {
	'erangel' : r'Maps\Erangel\Art\Heightmap', 
	'savage' : r'Maps\Savage\Art\Heightmap',
	'miramar' : r'Maps\Desert\Art\Heightmap' }

Added savage to PathsByMap

asset_path = os.path.join(umodel_heightmap_path, 'Heightmap_x%d_y%d_sharedAssets\Texture2D_%d.tga')

removed 0%d from asset_path

tile_path = asset_path % (offsets[0], offsets[1], tile_index)

removed i from tile_path

**Comment by cgcostume** [comment]
thanks for the feedback, the stitching is off due to the smaller size of the savage map (only 4k instead of 8k), so its only a quarter of the size as well as number of tiles. The latest commit (75e0a88d9bef1e5569d0121bcc5a614dfd10a2dd) should allow you to extract the smaller maps:
```
.\pubg-tga-slice.py -p .\UmodelExport\ -m sahok
```
I tested this for the experimental server and will provide the maps when officially released.
